### ISSUE TITLE
Bad documentation about value property

### ISSUE THREAD

**Issue by bigboban** [enkama/hass-variables#127]
I upgraded from 2.x version to last. So i went to doc to read how to do everything in new version.

In table below variable.update_sensor is only "value" property alone. But it does NOT work. Right is something like this:

```
    - service: variable.update_sensor
      target:
        entity_id: xxx
      data:  
        value: 10

```

Add "data" to your doc please.
