### ISSUE TITLE
The automation "X" has an unknown action: variable.update_sensor

### ISSUE THREAD

**Issue by townsmcp** [enkama/hass-variables#130]
Hi,
I just updated HA to 2024.7.4 and this integration to 3.4.7 however after a reboot I am getting an error stating:
Lux - Upstairs Hall uses an unknown action
The automation "Lux - Upstairs Hall" (automation.lux_upstairs_hall) has an unknown action: variable.update_sensor.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.1.198:8123/config/automation/edit/1690639714419) and remove this action.

Click on SUBMIT below to confirm you have fixed this automation.

![Screen Shot 2024-07-30 at 16 41 04](https://github.com/user-attachments/assets/640dbbd7-811b-4ebc-8341-288708fd1159)

The automations I have are all based on the same principal - when lux levels change for a given sensor, update the created history sensor with the new lux level. An example automation is:
```
alias: Lux - Upstairs Hall
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.upstairs_hall_lux_sensor_illuminance_lux
    attribute: illuminance_lux
condition:
  - condition: state
    entity_id: light.upstairs_hall_lights
    state: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 30
  - condition: sun
    after: sunrise
    before: sunset
    before_offset: "01:00:00"
    after_offset: "-01:00:00"
    enabled: true
action:
  - service: variable.update_sensor
    data:
      value: "{{states('sensor.upstairs_hall_lux_sensor_illuminance_lux')}}"
      replace_attributes: false
    target:
      entity_id: sensor.lux_upstairs_hall
mode: single
```

Also, I can perform a call service from developers tools and use the following code and the sensor lux values are updated correctly without any errors:
```
service: variable.update_sensor
data:
  value: "{{states('sensor.upstairs_hall_lux_sensor_illuminance_lux')}}"
  replace_attributes: false
target:
  entity_id: sensor.lux_upstairs_hall
```

Although I am getting this error, the sensors do seem to be updating with their lux levels. Any ideas why I am getting the errors? And what I would need to do to correct the errors?
