### ISSUE TITLE
Feature or Knowledge? How to delete attribute for "restore: true"

### ISSUE THREAD

**Issue by pickonedev** [enkama/hass-variables#134]
Hi!

I have a question, I don't know if you already can do this with the current version of the addon, or it could be a feature request...
Let's say that I have a sensor like this:

```
variable_last_state:
  name: Last State Entities
  value: "ok"
  restore: true
  attributes:
    switch_toilet_toothbrush: 0
    switch_bathroom_toothbrush: 0
    switch_bathroom_water_flosser: 0
```

In this moment, if I want to delete an attribute, I need to delete the line attribute from yaml, then set the `restore` to false, restart HA or reload yaml, then set `restore` back to true and another restart.

There is any other way to remove attributes?
Something easy like: delete the line attribute from yaml (just to not create confusion in the future), then run a service action somehow...

Thank you!

**Comment by Snuffy2** [comment]
Initial:
<img width="817" alt="2024-10-27_18-26-02 146" src="https://github.com/user-attachments/assets/52b344ab-a635-4b1a-90f9-be0aa0bedda0">

Run this action:
```yaml
action: variable.update_sensor
target:
  entity_id: sensor.variable_last_state
data:
  replace_attributes: true
  attributes:
    switch_bathroom_toothbrush: 1
    switch_bathroom_water_flosser: 1
```

After:
<img width="814" alt="2024-10-27_18-28-40 153" src="https://github.com/user-attachments/assets/d3433032-3511-4932-9fdd-61b68bb8b515">


If I understand correctly, you just need to use `replace_attributes: true` when calling the `variable.update_sensor` action.
